# Data comparisson on replay memory

# Pickle

In [1]:
import pickle
import numpy as np

In [2]:
%time [storage,next_idx]=pickle.load(open('rpm_expert.pickle','rb'))

CPU times: user 52.1 ms, sys: 23.8 ms, total: 75.8 ms
Wall time: 75.3 ms


In [3]:
storage[0]

(array([ 0.92520818, -0.37945992,  0.62307389]),
 array([2.]),
 -0.19430846659192988,
 array([ 0.93684856, -0.34973529,  0.63847895]),
 0)

In [31]:
%time pickle.dump([storage,next_idx],open('rpm.pkl','wb'))

CPU times: user 180 ms, sys: 7.94 ms, total: 188 ms
Wall time: 187 ms


# cPickle

In [13]:
import _pickle as cPickle

In [58]:
%time [storage,next_idx]=cPickle.load(open('rpm_expert.pickle','rb'))

CPU times: user 101 ms, sys: 46 µs, total: 101 ms
Wall time: 97.4 ms


In [36]:
%time cPickle.dump([storage,next_idx],open('rpm.cpkl','wb'))

CPU times: user 181 ms, sys: 7.76 ms, total: 188 ms
Wall time: 187 ms


In [37]:
%time [storage,next_idx]=cPickle.load(open('rpm.cpkl','rb'))

CPU times: user 81.4 ms, sys: 246 µs, total: 81.7 ms
Wall time: 78.5 ms


# Json

In [45]:
from json_tricks import dump, dumps, load, loads, strip_comments

In [52]:
with open('rpm.json', 'w') as outfile:
    %time dump(storage,outfile)

CPU times: user 5.77 s, sys: 3.87 ms, total: 5.78 s
Wall time: 5.78 s


# uJson

In [72]:
len(storage)

20000

# H5py with Hickle

In [4]:
import hickle

/home/daniel/anaconda3/envs/data-types/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
%time hickle.dump(storage,open('rpm.hkl','w'))

CPU times: user 39.1 s, sys: 884 ms, total: 40 s
Wall time: 43.1 s


# H5py

In [7]:
import h5py

In [ ]:
for sample in storage

In [14]:
with h5py.File('rpm.h5', 'w') as f:
    def write(dsetname, a):
        f.create_dataset(dsetname, data=a, compression='gzip')
    # Samples
    for sample in storage:
        write('obs', sample[0])
        write('action', sample[1])
        write('obs1', sample[2])
        write('reward', sample[3]))

TypeError: Scalar datasets don't support chunk/filter options

# 